services:
  - type: web
    name: freelancehub
    env: python
    pythonVersion: "3.11.8"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir freelancehub app:app --workers 2 --threads 2 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
